{% set version = "1.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-caper
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/caper_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/caper/caper_{{ version }}.tar.gz
  sha256: bcbeb788983e2cad656afb166f6f979fb67fb432a60fc35160d9447e6dfac2b1

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-mass
    - r-ape >=3.0_6
    - r-mvtnorm
  run:
    - r-base
    - r-mass
    - r-ape >=3.0_6
    - r-mvtnorm

test:
  commands:
    - $R -e "library('caper')"           # [not win]
    - "\"%R%\" -e \"library('caper')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=caper
  license: GPL-2.0-or-later
  summary: Functions for performing phylogenetic comparative analyses.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut
