travis:
  secure:
    BINSTAR_TOKEN: lv555+tLHh12SfEFN4SHj8JPHXlETBbOH0RvsmTCbPL/583gl5cniHWLKfyCMnrPdw6BPhxNKuCE2cHFeKluSjq58LPZF1Wj3mzouvtdqnM4vh2bErLlM0twbh+m8TSyqECsyz96x/grcwhi0QfwhTQk1804XxaOtyuFnEQNPZvExI7yDu56gTBM8Wm0OAeGioJGTUFgXDvFAC7Y2i3JeCSt249w1L5aCj8WpZ4GZdLV4e8eAOsQS7ERez1JlLllovKM5sBRXti0g/OW5u/AUg1qWblpfKbZWAZ9kQXDZoE6wWrn/rYyP/LYpAvEau642uQnLA71X4wo05kaROBcr6DnOnFEZP+W5i15qQp97UzswQayx3nowa8WZ7sf9yMT28Qluh1PhAUmyujEXyEcPwVWPQRYiP2bKX/LIYV6y/PgquZTlP820WwQCT3gNZwr4L7VpIq33tsRgCDNDXAmLkjxkgdmDwMs45PbzXyof90ZN6QucWwW5Yp1anys7XfCANSQsYluCSKuEJU3Cq+PfwzFfFEEV/SVy1PMQJzM5+q8OFvyNQT2N/NxwLN9/1vdr85qA9sZmoddPiy7vPPGttxoY4lR8BmP5LFLRMrFPWDdCljb3PNOZnC0oXEsYrgMwyTCvRtPKjD3DgKA+mHwYpqE8q0Nv4hiOoLyrxA27kk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
