travis:
  secure:
    BINSTAR_TOKEN: FAaawwIufnckMHOadv0Tsebai4xcHUlgRWXWsh2hfculGeh70QZRPqDerrq2ToZZ02Dp+BuFfCl6lJKisO9PoMZK+HGg1GOvP8BxUhV0+jf1Rc5U1cBqTbjZKQXQaast8x/6OZWAB4wv5FN4jV8EdRGFwT7gVpCFX4Jt8f0SeM9XWneW8pKaRU0AKgi4svPHU7FCOi9y9sf3tKJ8qPgFPAfU0NHonR2av1MQ2qAq4zmD41YclXfDPG/XSiIJtsySFNQbSbmmtgTl3CimgScR/29mwREZ7JeyL01MQ6ShGXhNzmnEEHASI5WuRD+r9axF/uEYFApq6VcjgvlC7KmauMHToGj3QceMCQNTA1vIWAVFrs11cZxSt7A/BUyb+SquHQ8mchEeY4aSsLdO3YvLzYMv/wBKX6RdS78hEHnd35hJvqmfGGcEt56LqE96GN44K8meELytfbgkE//Wg2wNT+Rk33EAO2m7ivnhVkMWDTsoxCTrUo5xpn/XErP4oKFHZBHYmhgiwq9qSqaxYR6ifZDDeaYEG87M4K1DKSaWk/gdEvoc99l8Qt+ZW/K7tIR8VQwwVRSdp9T/ZMRoWhkE/LiCTv4iyksPy0KWkMSuWP/3HijOy99Tf0OLzxWbudzhlFKEXuXChcmIvAdIF9qNKUwDFZN6Gu9038W+gBsfu0E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
