appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZWks7azVYT/InGLb9m1Fr2TaembQwSY5llT38v+H2/n89y8DLDVZrPEeZP4e5D1QIsyciyt18Q1JLq2EvK1heQsKQqomJKmetjjfwDD/racQIu4OAPZaYp1sNQmPOhC/IVlr4fHhVIiGhhc7zKcmECIA1jqtpTEAFap0GWWgHdXbGVX+Cu9Hr+sy2X8YGpNNj1bJ1cXkSv4oEypgTEpD6Td4fuUlDll4q1lEKLbUfOsDRX5m7mpzQ5oMDJe86C0Rk7JVEvqyyOQ0aynOwkJ00rSeVLnkYLVtSyYOH0JHtw1YB9ZxFkJggINmJuIMSz3YnGMg4e5+BSWE6YjU+uEL4bCfwFwNfa3h1oS4kRclUBlrWOQFqB/VLk6RP58mtzFPbMAPW+xLZhH5AhNFxARWCbnZnojOo+UBqiIChlMerGdR1Q6BJLgTR4fofDmJ+A9My8U5NE7G1Pykzcvs42UcXDAiB0xfPKdY2AiNW5mVkozq27P47Bc2J9/11Q8Rm6lwJWb+YLxaf5ew2lu9J6XKLCxb0+WrSd1O/w47o6HEbAuF1fwHXYiAX0p7oHivs60p5G22eD4MYfA1nI8I32l5i2Cb8wGQQHXCM4g0FTfwuNbXh6D77rGtnIpYuA+UA+qagJamklj5UeyhvUnPZLZTAzWMaNxIMaAKz5mwmYmBFB4=}
